package cn.et.lesson03.entity;

public class Food {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.foodid
     *
     * @mbg.generated Fri Dec 08 19:17:50 CST 2017
     */
    private Integer foodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.foodname
     *
     * @mbg.generated Fri Dec 08 19:17:50 CST 2017
     */
    private String foodname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.money
     *
     * @mbg.generated Fri Dec 08 19:17:50 CST 2017
     */
    private Integer money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.foodid
     *
     * @return the value of food.foodid
     *
     * @mbg.generated Fri Dec 08 19:17:50 CST 2017
     */
    public Integer getFoodid() {
        return foodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.foodid
     *
     * @param foodid the value for food.foodid
     *
     * @mbg.generated Fri Dec 08 19:17:50 CST 2017
     */
    public void setFoodid(Integer foodid) {
        this.foodid = foodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.foodname
     *
     * @return the value of food.foodname
     *
     * @mbg.generated Fri Dec 08 19:17:50 CST 2017
     */
    public String getFoodname() {
        return foodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.foodname
     *
     * @param foodname the value for food.foodname
     *
     * @mbg.generated Fri Dec 08 19:17:50 CST 2017
     */
    public void setFoodname(String foodname) {
        this.foodname = foodname == null ? null : foodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.money
     *
     * @return the value of food.money
     *
     * @mbg.generated Fri Dec 08 19:17:50 CST 2017
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.money
     *
     * @param money the value for food.money
     *
     * @mbg.generated Fri Dec 08 19:17:50 CST 2017
     */
    public void setMoney(Integer money) {
        this.money = money;
    }
}